name: 03 - Workflow Runners
on:
    push:
jobs:
    echo-ubuntu-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This is ubuntu os"
                echo "Runner OS: $RUNNER_OS"
            