name: 04 - using actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: list files and folders
              run: ls
              working-directory: 04-using-actions/react-app
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x' # Specify the Node.js version you need
            - name: Install dependencies
              run: npm ci
              working-directory: 04-using-actions/react-app
            - name: Run NPM Test
              run: npm run test
              working-directory: 04-using-actions/react-app  
