name: 08 - Using Variables
on: 
    push:
    workflow_dispatch:
env:
    WORKFLOW_VAR: "I am a Workflow env variable"
    OVERWRITTEN: "I will be overwritten"
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a job env variable"
            OVERWRITTEN: "I have been overwritten at the job level"
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: "I am a step Env Variable"
                step_var2: "I am another step env variable"
              run: |
                echo "Step env variable: ${{ env.STEP_VAR }}"
                echo "Step env variable2: $step_var2"
                echo "Job env variable: ${{ env.JOB_VAR }}"
                echo "Workflow env variable: ${{ env.WORKFLOW_VAR }}" 
                echo "Overwritten env variable: ${{ env.OVERWRITTEN }}" 
            - name: Overwritten job variable
              env:
                OVERWRITTEN: "I have been overwritten at the step level"
              run: |
                echo "Step env variable: ${{ env.OVERWRITTEN }}"
