name: 15 - Working with Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatability:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                node-version: [ 18.x, 20.x, 21.x ]
                os:
                    - ubuntu-latest
                    - windows-latest
                include: 
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental

        steps: 
            - name: Setup Node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Fail if experimental
              if: matrix.tag  == 'experimental'
              run: exit 1
            - name: Perform some tests
              run: |
                echo "Running on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                sleep 20
            - name: Upload test results
              run: echo "Uploading test results"
    include-example:
        name: ${{ matrix.colour }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                colour: [red, green]
                shape: [circle, square]
                size: [small,large]
                include:
                    - opacity: 50
                    - colour: red
                      opacity: 75
                    - shape: circle
                      opacity: 100
                    - colour: red
                      shape: triangle
        steps:
            - name: Dummy Step
              run: echo "${{ matrix.colour }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"