name: 16 - Working with Environments

on:
    workflow_dispatch:

    
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Deploying to Staging Env
              run: |
                echo "Deploying to Staging"
    
    e2e-test:
        runs-on: ubuntu-latest
        needs: deploy-staging
        steps:
            - name: E2E Test
              run: echo "Running E2E Test"
    deploy-prod:
        runs-on: ubuntu-latest
        needs: e2e-test
        environment: prod
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Deploying to Producion Env
              run: |
                echo "Deploying to Producion"
